version: "3.9"
services:
  urta_db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: "urta"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "7432:5432"
    volumes:
#      - pgdata:/var/lib/postgresql/data
      - ../../database:/docker-entrypoint-initdb.d
#volumes:
#  pgdata: